### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by unickq** [allure-framework/allure-csharp#18] opened 2018-09-26 08:48 UTC
Hi @Bakanych ,

Current implementation of  _AllureLifecycle.Instance_ expects to find _allureConfig.json_ in the same dir Allure.Commons.dll is. But 
```csharp
public AllureLifecycle() : this(Path.Combine(Path.GetDirectoryName(typeof (AllureLifecycle).Assembly.Location), AllureConstants.CONFIG_FILENAME))
{
}
```

Just tested 2.4.1.1 with .netCore 2.1 and found that Allure.Commons.dll is not in outDir, so allureConfig.json written in VS couldn't be found. Nuget path:
`C:\Users\%USER%\.nuget\packages\allure.commons\2.4.1.1\lib\netstandard2.0\Allure.Commons.dll`

So there need to be a way to set a path of allure config, since you disabled config property setters https://github.com/allure-framework/allure-csharp/issues/16

Maybe smth like:
```
AllureLifecycle.SetInstance(new AllureLifecycle("json"))
AllureLifecycle.SetInstance(new AllureConfiguration())
```

**Comment by Bakanych** [comment] 2018-09-26 09:06
Hi @unickq 

> and found that Allure.Commons.dll is not in outDir

Can you please help to explain where is the assembly location and why config cannot be placed there?

**Comment by unickq** [comment] 2018-09-26 09:33
@Bakanych 
Allure assembly location:
```C:\Users\%USER%\.nuget\packages\allure.commons\2.4.1.1\lib\netstandard2.0```
OutDir:
```bin\Debug\netcoreapp2.1\```

https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
> Solution-local packages folders are no longer used – Packages are now resolved against the user’s cache at %userdata%.nuget, rather than a solution specific packages folder. This makes PackageReference perform faster and consume less disk space by using a shared folder of packages on your workstation.

And about
> why config cannot be placed there?

You mean the manual creation of allureConfig.json in **typeof(AllureLifecycle).Assembly.Location** dir before calling **AllureLifecycle.Instance**?

**Comment by Bakanych** [comment] 2018-10-12 03:43
These days are very busy, will try to check this out next week...
I don't have quick solution so far, but I really don't like idea to allow changing configuration of static Allure.Instance in run time, as it can lead to unpredictable behavior.

**Comment by stephenmwilliams** [comment] 2018-11-05 21:31
@Bakanych, in addition to what @unickq has mentioned with the assembly going into nupkg, in the instances where shadowcopy kicks in, this results in the allure.commons dll being copied to AppData\Local\assembly\dl3 which means that it's not easily predictable where the allureConfig.json file should be placed.

**Comment by undron** [comment] 2018-11-06 07:50
How about environment variable with allure config location? 
`SET ALLURE_CONFIG=%appdata%\Local\assembly\dl3`

**Comment by stephenmwilliams** [comment] 2018-11-06 08:04
I'll give that a go, I couldn't see anything in allure commons which read that variable when initializing or calling the constructor.

Even still, the problem is the path isn't consistent between machines. The dl3 is just the parent folder, the assembly is about 3 folders below that with seemingly unpredictable folder names.

It feels as though we need a way to be able to define the config folder through app.config, or have allure lifecycle look for the file in the assembly location of the main application not the allure commons dll, as with specflow the feature .cs files are auto generated which limits options for intercepting the initialization steps.

**Comment by IiroS** [comment] 2018-12-21 10:38
I was able to resolve this issue by making a small configuration to .net core **.csproj** file.

`<PropertyGroup>`
`  <TargetFramework>netcoreapp2.1</TargetFramework>`
**`  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`**
`</PropertyGroup>`

This means that the nuget package dll  files are copied to build output folder and then the Allure.Commons.dll is used from the output directory where the allureConfig.json file is. But this also requires a configuration for allureConfig.json file so that it will be copied to output folder during the build.

`<ItemGroup>`
`<None Update="allureConfig.json">`
**`<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>`**
`</None>`
`</ItemGroup>`


I still think that the code which instantiates singleton instance for AllureLifeCycle should be fixed, but with this small hack you can live with the current implementation.

**Comment by Bakanych** [comment] 2019-01-02 02:35
hi @shahidsayyad, Current version of Specflow adapter supports Specflow 2.x only. Could you please try it with v2? I'll update requirement constraints meanwhile to avoid such usage in future.

**Comment by Bakanych** [comment] 2019-01-02 04:07
> I was able to resolve this issue by making a small configuration to .net core **.csproj** file.
> 
> `<PropertyGroup>`
> ` <TargetFramework>netcoreapp2.1</TargetFramework>`
> **` <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`**
> `</PropertyGroup>`
> 
> This means that the nuget package dll files are copied to build output folder and then the Allure.Commons.dll is used from the output directory where the allureConfig.json file is. But this also requires a configuration for allureConfig.json file so that it will be copied to output folder during the build.
> 
> `<ItemGroup>`
> `<None Update="allureConfig.json">`
> **`<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>`**
> `</None>`
> `</ItemGroup>`
> 
> I still think that the code which instantiates singleton instance for AllureLifeCycle should be fixed, but with this small hack you can live with the current implementation.

thanks for this nice workaround!

**Comment by Bakanych** [comment] 2019-01-02 10:44
Hi all and happy New Year!
Please check new version with updated configuration read. Thanks @undron for the idea!

**Closed** 2019-03-15 06:57 UTC

**Comment by satheeshcvcet** [comment] 2019-10-03 11:53
When I installing Specflow3.Allure in .net core, I am getting issue "Message: Value cannot be null.
Parameter name: key" on running specflow test cases.

**Comment by singh-swati28** [comment] 2021-11-08 23:59
Hi,
I am trying to use Allure with SpecFlow in netcoreapp3.1 framework using Spec Runner. I created 'allureConfig.json' and set it to be copied to output dir always, but while running my tests, its not getting read and I cannot see configurations like issue link, author/owner given in allureConfig.json.

PS: When I am setting Environment variable ALLURE_CONFIG in my local machine or in 'Default.srprofile', then its reading allureConfig.json file 

Also, if I use SpecFlow SpecFlow NUnit Runner instead of Spec Runner, then also its working.

Please suggest how to use allureConfig.json file with Specflow SpecRun.

**Comment by singh-swati28** [comment] 2021-11-09 00:06
@Bakanych @IiroS  Please suggest
